import {
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Download,
  Image,
  Info,
  KeyRound,
  Layers,
  LayoutGrid,
  ListFilter,
  LogOut,
  Menu,
  MoreVertical,
  Package,
  Pencil,
  Plus,
  RotateCcw,
  Search,
  Shield,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Sun,
  Moon,
  Trash2,
  TriangleAlert,
  Truck,
  Upload,
  Users,
  X,
} from 'lucide-react';

const ICONS = {
  grid: LayoutGrid,
  shield: Shield,
  sliders: SlidersHorizontal,
  key: KeyRound,
  calendar: Calendar,
  users: Users,
  phone: Smartphone,
  truck: Truck,
  box: Package,
  sun: Sun,
  moon: Moon,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  menu: Menu,
  close: X,
  logout: LogOut,
  sparkles: Sparkles,
  clock: Clock,
  reset: RotateCcw,
  check: Check,
  layers: Layers,
  filter: ListFilter,
  search: Search,
  info: Info,
  image: Image,
  download: Download,
  upload: Upload,
  trash: Trash2,
  plus: Plus,
  edit: Pencil,
  dots: MoreVertical,
  alert: TriangleAlert,
};

export const Icon = ({ name, className = 'size-4', strokeWidth = 1.75 }) => {
  const Glyph = ICONS[name];
  if (!Glyph) return null;
  return <Glyph className={className} strokeWidth={strokeWidth} aria-hidden="true" />;
};

export default Icon;
